"""create designs table

Revision ID: 13cd81931b02
Revises: 9f1672003a14
Create Date: 2026-06-23 12:02:20.261708

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13cd81931b02'
down_revision: str | None = '9f1672003a14'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requirements_json', sa.JSON(), nullable=True),
    sa.Column('capacity_json', sa.JSON(), nullable=True),
    sa.Column('architecture_json', sa.JSON(), nullable=True),
    sa.Column('database_json', sa.JSON(), nullable=True),
    sa.Column('api_json', sa.JSON(), nullable=True),
    sa.Column('diagram_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designs_project_id'), 'designs', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designs_project_id'), table_name='designs')
    op.drop_table('designs')
    # ### end Alembic commands ###
