from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict


class DesignUpdate(BaseModel):
    """Partial update — only the provided fields are written.

    Each section is generated by a different milestone, so updates are
    typically partial (e.g. only ``requirements_json`` after Milestone 5).
    """

    requirements_json: Any | None = None
    capacity_json: Any | None = None
    architecture_json: Any | None = None
    database_json: Any | None = None
    api_json: Any | None = None
    diagram_text: str | None = None


class DesignOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    project_id: int
    requirements_json: Any | None
    capacity_json: Any | None
    architecture_json: Any | None
    database_json: Any | None
    api_json: Any | None
    diagram_text: str | None
    created_at: datetime
    updated_at: datetime
